@extends('admin.layouts.app', ['title' => 'User Accounts | MCARE Admin'])

@section('content')
<section class="space-y-6">
    <header class="border-b border-slate-200 pb-6"><p class="dashboard-section-kicker">Administration - Accounts</p><h1 class="dashboard-section-title mt-2 text-3xl">Trainer and trainee accounts</h1><p class="mt-2 text-sm leading-6 text-slate-600">Create role-specific sign-in accounts. Admin-created trainees are immediately approved and assigned to the selected batch.</p></header>

    <div class="grid gap-6 xl:grid-cols-2">
        <form method="POST" action="{{ route('admin.accounts.trainers.store') }}" class="dashboard-panel space-y-4">
            @csrf
            <div><p class="dashboard-section-kicker">Add trainer</p><h2 class="dashboard-section-title mt-1">Trainer account</h2></div>
            <div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Full name</label><input name="name" value="{{ old('name') }}" class="form-field" required></div>
            <div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Email</label><input name="email" type="email" value="{{ old('email') }}" class="form-field" required></div>
            <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Temporary password</label><input name="password" type="password" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Confirm password</label><input name="password_confirmation" type="password" class="form-field" required></div></div>
            <button class="primary-action">Create trainer</button>
        </form>

        <form method="POST" action="{{ route('admin.accounts.trainees.store') }}" class="dashboard-panel space-y-4">
            @csrf
            <div><p class="dashboard-section-kicker">Add trainee</p><h2 class="dashboard-section-title mt-1">Approved trainee account</h2></div>
            <div class="grid gap-4 md:grid-cols-3"><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">First name</label><input name="first_name" value="{{ old('first_name') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Middle name</label><input name="middle_name" value="{{ old('middle_name') }}" class="form-field"></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Last name</label><input name="last_name" value="{{ old('last_name') }}" class="form-field" required></div></div>
            <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Email</label><input name="email" type="email" value="{{ old('email') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Contact number</label><input name="contact_number" value="{{ old('contact_number') }}" class="form-field" required></div></div>
            <div class="grid gap-4 md:grid-cols-3"><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Birth date</label><input name="birth_date" type="date" value="{{ old('birth_date') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Gender</label><select name="gender" class="form-field" required><option value="">Select</option><option @selected(old('gender') === 'Male')>Male</option><option @selected(old('gender') === 'Female')>Female</option></select></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Schedule</label><select name="schedule_preference" class="form-field" required><option value="AM" @selected(old('schedule_preference') === 'AM')>AM</option><option value="PM" @selected(old('schedule_preference') === 'PM')>PM</option></select></div></div>
            <div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Batch</label><select name="training_batch_id" class="form-field" required><option value="">Select batch</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected((int)old('training_batch_id') === $batch->id)>{{ $batch->name }} {{ $batch->year }}</option>@endforeach</select></div>
            <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Number and street</label><input name="street" value="{{ old('street') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Barangay</label><input name="barangay" value="{{ old('barangay') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">City</label><input name="city" value="{{ old('city') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Province</label><input name="province" value="{{ old('province') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">ZIP code</label><input name="zip_code" value="{{ old('zip_code') }}" class="form-field" required></div></div>
            <div class="grid gap-4 md:grid-cols-3"><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Educational attainment</label><input name="educational_attainment" value="{{ old('educational_attainment') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">School</label><input name="school_name" value="{{ old('school_name') }}" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Year graduated</label><input name="year_graduated" type="number" min="1950" max="{{ now()->year }}" value="{{ old('year_graduated') }}" class="form-field" required></div></div>
            <div class="grid gap-4 md:grid-cols-2"><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Temporary password</label><input name="password" type="password" class="form-field" required></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Confirm password</label><input name="password_confirmation" type="password" class="form-field" required></div></div>
            @if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><p class="font-bold">Please review the form:</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <button class="primary-action">Create trainee</button>
        </form>
    </div>

    <div class="dashboard-table-wrap overflow-x-auto"><table class="dashboard-table min-w-[52rem]"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Created</th></tr></thead><tbody>@forelse($accounts as $account)<tr><td class="font-bold text-slate-900">{{ $account->name }}</td><td>{{ $account->email }}</td><td><span class="dashboard-pill bg-purple-50 text-purple-700 ring-purple-100">{{ str($account->role)->headline() }}</span></td><td>{{ $account->created_at?->format('M d, Y g:i A') }}</td></tr>@empty<tr><td colspan="4" class="py-12 text-center">No trainer or trainee accounts yet.</td></tr>@endforelse</tbody></table>@if($accounts->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $accounts->links() }}</div>@endif</div>
</section>
@endsection
