@extends('admin.layouts.app', ['title' => 'Certificate Eligibility | MCARE Admin'])

@section('content')
<section class="space-y-6">
    <header class="border-b border-slate-200 pb-6"><p class="dashboard-section-kicker">Learning system · Certificates</p><h1 class="mt-2 dashboard-section-title text-3xl">Certificate eligibility queue</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600">This is an eligibility checkpoint, not certificate generation yet. Attendance, assessments, competency, and trainer completion will join this gate in the next LMS phase.</p></header>
    <form method="GET" class="dashboard-panel grid gap-4 md:grid-cols-4"><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Batch</label><select name="batch_id" class="form-field"><option value="">All batches</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected((int)($filters['batch_id'] ?? 0) === $batch->id)>{{ $batch->name }} {{ $batch->year }}</option>@endforeach</select></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Schedule</label><select name="schedule" class="form-field"><option value="">AM and PM</option><option value="AM" @selected(($filters['schedule'] ?? '') === 'AM')>AM</option><option value="PM" @selected(($filters['schedule'] ?? '') === 'PM')>PM</option></select></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Current signal</label><select name="eligibility" class="form-field"><option value="">All</option><option value="eligible" @selected(($filters['eligibility'] ?? '') === 'eligible')>Approved + paid</option><option value="blocked" @selected(($filters['eligibility'] ?? '') === 'blocked')>Payment blocked</option></select></div><div class="flex items-end gap-2"><button class="primary-action">Filter</button><a href="{{ route('admin.learning.certificates') }}" class="secondary-action">Reset</a></div></form>
    <div class="dashboard-table-wrap overflow-x-auto"><table class="dashboard-table min-w-[58rem]"><thead><tr><th>Trainee</th><th>Batch</th><th>Schedule</th><th>Approval</th><th>Payment gate</th><th>Certificate state</th></tr></thead><tbody>
    @forelse($records as $record)<tr><td><p class="font-bold text-slate-950">{{ $record->last_name }}, {{ $record->first_name }}</p><p class="mt-1 text-xs">{{ $record->email }}</p></td><td>{{ $record->batch ? $record->batch->name.' '.$record->batch->year : 'Unassigned' }}</td><td>{{ $record->schedule_preference }}</td><td>{{ $record->statusLabel() }}</td><td>{{ $record->paymentStatusLabel() }}</td><td><span class="dashboard-pill {{ $record->payment_status === 'paid' ? 'bg-emerald-50 text-emerald-700 ring-emerald-100' : 'bg-amber-50 text-amber-700 ring-amber-100' }}">{{ $record->payment_status === 'paid' ? 'Ready for LMS checks' : 'Blocked by payment' }}</span></td></tr>
    @empty<tr><td colspan="6" class="py-14 text-center">No trainee records match these filters.</td></tr>@endforelse
    </tbody></table>@if($records->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $records->links() }}</div>@endif</div>
</section>
@endsection
