@extends('admin.layouts.app', ['title' => 'LMS Module Oversight | MCARE Admin'])

@section('content')
<section class="space-y-6">
    <header class="border-b border-slate-200 pb-6"><p class="dashboard-section-kicker">Learning system · LMS Modules</p><h1 class="mt-2 dashboard-section-title text-3xl">Module oversight</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600">See every trainer upload, assigned batch, and publication state without mixing modules into the trainee queue.</p></header>
    <form method="GET" class="dashboard-panel grid gap-4 md:grid-cols-4"><div class="md:col-span-2"><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Search module or trainer</label><input name="search" value="{{ $filters['search'] ?? '' }}" class="form-field"></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Batch</label><select name="batch_id" class="form-field"><option value="">All batches</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected((int)($filters['batch_id'] ?? 0) === $batch->id)>{{ $batch->name }} {{ $batch->year }}</option>@endforeach</select></div><div><label class="mb-2 block text-xs font-bold uppercase text-slate-500">Publication</label><select name="published" class="form-field"><option value="">All states</option><option value="yes" @selected(($filters['published'] ?? '') === 'yes')>Published</option><option value="no" @selected(($filters['published'] ?? '') === 'no')>Draft</option></select></div><div class="flex gap-2 md:col-span-4"><button class="primary-action">Filter modules</button><a href="{{ route('admin.learning.modules') }}" class="secondary-action">Reset</a></div></form>
    <div class="dashboard-table-wrap overflow-x-auto"><table class="dashboard-table min-w-[54rem]"><thead><tr><th>Module</th><th>Trainer</th><th>Batch</th><th>File</th><th>Publication</th></tr></thead><tbody>
    @forelse($modules as $module)<tr><td><p class="font-bold text-slate-950">{{ $module->title }}</p><p class="mt-1 max-w-md text-xs line-clamp-2">{{ $module->description }}</p></td><td>{{ $module->trainer?->name ?? 'Unassigned' }}</td><td>{{ $module->batch ? $module->batch->name.' '.$module->batch->year : 'General' }}</td><td><span class="break-all text-xs">{{ $module->original_file_name }}</span></td><td><span class="dashboard-pill {{ $module->is_published ? 'bg-emerald-50 text-emerald-700 ring-emerald-100' : 'bg-slate-100 text-slate-700 ring-slate-200' }}">{{ $module->is_published ? 'Published' : 'Draft' }}</span><p class="mt-2 text-xs">{{ $module->published_at?->format('M d, Y g:i A') ?? 'Not published' }}</p></td></tr>
    @empty<tr><td colspan="5" class="py-14 text-center">No modules match these filters.</td></tr>@endforelse
    </tbody></table>@if($modules->hasPages())<div class="border-t border-slate-200 px-5 py-4">{{ $modules->links() }}</div>@endif</div>
</section>
@endsection
